#微服务一定要有端口号和端口名称
server:
  port: 8001

#  服务名称
spring:
  application:
    name: cloud-payment-Hystrix-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  circuitbreaker:
    enabled: true

